In [1]:
from icl_mi import mutual_Token
print('Initializing the model')
mt = mutual_Token.mutualToken()
qkov, ov_dict_list = mt.get_QKOV()
print('Calculating the information')
info = mt.calc_information()

/home/phu.hoang/.conda/envs/icl_mi/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


Initializing the model
Calculating the information


100%|██████████| 48/48 [02:05<00:00,  2.62s/it]


In [4]:
l45 = info[45]

In [5]:
l45.keys()

dict_keys(['h_1_w1_female', 'h_1_w2_ĉ', 'h_1_w3_middle', 'h_1_w4_ĉ', 'h_1_w5_28', 'h_1_w6_Ġ->', 'h_1_w7_Ġsurvival', 'h_1_w8_Ċ', 'h_1_w9_male', 'h_1_w10_ĉ', 'h_1_w11_upper', 'h_1_w12_ĉ', 'h_1_w13_51', 'h_1_w14_Ġ->', 'h_1_w15_Ġdeath', 'h_1_w16_Ċ', 'h_1_w17_male', 'h_1_w18_ĉ', 'h_1_w19_lower', 'h_1_w20_ĉ', 'h_1_w21_21', 'h_1_w22_Ġ->', 'h_2_w1_female', 'h_2_w2_ĉ', 'h_2_w3_middle', 'h_2_w4_ĉ', 'h_2_w5_28', 'h_2_w6_Ġ->', 'h_2_w7_Ġsurvival', 'h_2_w8_Ċ', 'h_2_w9_male', 'h_2_w10_ĉ', 'h_2_w11_upper', 'h_2_w12_ĉ', 'h_2_w13_51', 'h_2_w14_Ġ->', 'h_2_w15_Ġdeath', 'h_2_w16_Ċ', 'h_2_w17_male', 'h_2_w18_ĉ', 'h_2_w19_lower', 'h_2_w20_ĉ', 'h_2_w21_21', 'h_2_w22_Ġ->', 'h_3_w1_female', 'h_3_w2_ĉ', 'h_3_w3_middle', 'h_3_w4_ĉ', 'h_3_w5_28', 'h_3_w6_Ġ->', 'h_3_w7_Ġsurvival', 'h_3_w8_Ċ', 'h_3_w9_male', 'h_3_w10_ĉ', 'h_3_w11_upper', 'h_3_w12_ĉ', 'h_3_w13_51', 'h_3_w14_Ġ->', 'h_3_w15_Ġdeath', 'h_3_w16_Ċ', 'h_3_w17_male', 'h_3_w18_ĉ', 'h_3_w19_lower', 'h_3_w20_ĉ', 'h_3_w21_21', 'h_3_w22_Ġ->', 'h_4_w1_female', 'h_

In [8]:
decoded_tokens = mt.get_token_dict()

In [9]:
decoded_tokens

['female',
 'ĉ',
 'middle',
 'ĉ',
 '28',
 'Ġ->',
 'Ġsurvival',
 'Ċ',
 'male',
 'ĉ',
 'upper',
 'ĉ',
 '51',
 'Ġ->',
 'Ġdeath',
 'Ċ',
 'male',
 'ĉ',
 'lower',
 'ĉ',
 '21',
 'Ġ->']

In [12]:
for i in range(len(decoded_tokens)):
    print(f"MI from {decoded_tokens[i]} is {l45['h_1_w22_Ġ->'][i]}")

MI from female is 0.7135116952194509
MI from ĉ is 2.7186961039002275
MI from middle is 2.7012052370445443
MI from ĉ is 2.7961120170624656
MI from 28 is 2.7315486512610523
MI from Ġ-> is 3.013551813326429
MI from Ġsurvival is 2.718696103900228
MI from Ċ is 2.480491221121532
MI from male is 3.1188467363133032
MI from ĉ is 2.6740905887084567
MI from upper is 2.943141853534607
MI from ĉ is 2.801304798865899
MI from 51 is 3.0615395181167364
MI from Ġ-> is 2.785374329980682
MI from Ġdeath is 2.7193499160872032
MI from Ċ is 2.9023109464707453
MI from male is 2.935121344441212
MI from ĉ is 2.9278651968363656
MI from lower is 3.1245424859476825
MI from ĉ is 2.8790814555641404
MI from 21 is 2.978166461662516
MI from Ġ-> is 2.763955431278974


In [6]:
l45['h_1_w22_Ġ->']

[0.7135116952194509,
 2.7186961039002275,
 2.7012052370445443,
 2.7961120170624656,
 2.7315486512610523,
 3.013551813326429,
 2.718696103900228,
 2.480491221121532,
 3.1188467363133032,
 2.6740905887084567,
 2.943141853534607,
 2.801304798865899,
 3.0615395181167364,
 2.785374329980682,
 2.7193499160872032,
 2.9023109464707453,
 2.935121344441212,
 2.9278651968363656,
 3.1245424859476825,
 2.8790814555641404,
 2.978166461662516,
 2.763955431278974]

In [13]:
oss = qkov['attn_output_each_head']
vss = qkov['V']

In [94]:
vss[0].shape

torch.Size([1, 25, 22, 64])

In [50]:
os[0].shape

torch.Size([1, 25, 22, 64])

In [55]:
import numpy as np

# Parameters
seq_len = 4       # Number of words/tokens in the sequence
num_layer = 3     # Number of layers in the model
num_head = 5
dim = 2 

# Initialize the arrays using NumPy
vs, os, information = np.empty((3, num_layer, num_head, seq_len), dtype=object)

# synthesize data
# Define the shape of each NumPy array
array_shape = (1, num_head, seq_len, dim)

# Create a list of 3 NumPy arrays with the specified shape
array_list = [np.random.rand(*array_shape) for _ in range(num_layer)]


In [2]:
import numpy as np

# Initialize an empty list to hold the arrays
array_list_o = []
array_list_v = []

# Parameters
seq_len = 4       # Number of words/tokens in the sequence
num_layer = 3     # Number of layers in the model
num_head = 5
dim = 2 

# Populate the list with arrays
for _ in range(3):
    # Create an empty array of shape (1, 5, 4, 2)
    array_o = np.empty((1, 5, 4, 2), dtype=object)
    array_v = np.empty((1, 5, 4, 2), dtype=object)

    
    # Fill the array with the formatted strings
    for i in range(5):
        for j in range(4):
            for k in range(2):
                array_o[0, i, j, k] = f"o_h{i+1}_w{j+1}_d{k+1}"
    
    # Add the array to the list
    array_list_o.append(array_o)

    for i in range(5):
        for j in range(4):
            for k in range(2):
                array_v[0, i, j, k] = f"v_h{i+1}_w{j+1}_d{k+1}"
    
    # Add the array to the list
    array_list_v.append(array_v)


# Now array_list contains 3 arrays with the specified format
array_list_o[0], array_list_v[0]

(array([[[['o_h1_w1_d1', 'o_h1_w1_d2'],
          ['o_h1_w2_d1', 'o_h1_w2_d2'],
          ['o_h1_w3_d1', 'o_h1_w3_d2'],
          ['o_h1_w4_d1', 'o_h1_w4_d2']],
 
         [['o_h2_w1_d1', 'o_h2_w1_d2'],
          ['o_h2_w2_d1', 'o_h2_w2_d2'],
          ['o_h2_w3_d1', 'o_h2_w3_d2'],
          ['o_h2_w4_d1', 'o_h2_w4_d2']],
 
         [['o_h3_w1_d1', 'o_h3_w1_d2'],
          ['o_h3_w2_d1', 'o_h3_w2_d2'],
          ['o_h3_w3_d1', 'o_h3_w3_d2'],
          ['o_h3_w4_d1', 'o_h3_w4_d2']],
 
         [['o_h4_w1_d1', 'o_h4_w1_d2'],
          ['o_h4_w2_d1', 'o_h4_w2_d2'],
          ['o_h4_w3_d1', 'o_h4_w3_d2'],
          ['o_h4_w4_d1', 'o_h4_w4_d2']],
 
         [['o_h5_w1_d1', 'o_h5_w1_d2'],
          ['o_h5_w2_d1', 'o_h5_w2_d2'],
          ['o_h5_w3_d1', 'o_h5_w3_d2'],
          ['o_h5_w4_d1', 'o_h5_w4_d2']]]], dtype=object),
 array([[[['v_h1_w1_d1', 'v_h1_w1_d2'],
          ['v_h1_w2_d1', 'v_h1_w2_d2'],
          ['v_h1_w3_d1', 'v_h1_w3_d2'],
          ['v_h1_w4_d1', 'v_h1_w4_d2']],
 
       

In [5]:
import numpy as np

def extract_vectors(o_array, v_array):
    """
    Iterates through all heads (i) and all words (j), 
    extracting the o vector for each word j in head i 
    and all v vectors from word 1 to j in head i.

    Parameters:
    o_array (numpy array): Array of o vectors of shape (1, num_heads, num_words, num_dims)
    v_array (numpy array): Array of v vectors of shape (1, num_heads, num_words, num_dims)

    Returns:
    results (list): A list of tuples containing o_vector and v_vectors for each (i, j) combination
    """
    results = []
    
    # Extract the shape info from arrays (since first dimension is 1, we use index 0)
    num_heads = o_array.shape[1]
    num_words = o_array.shape[2]
    
    # Iterate over each head and word
    for i in range(num_heads):
        for j in range(1, num_words+1):  # 1-indexed for word loop
            # Extract o vector for word j in head i
            o_vector = o_array[0][i][j-1]  # Subtract 1 because of 1-based indexing
            
            # Extract v vectors for all words from word 1 to word j in head i
            v_vectors = [v_array[0][i][w] for w in range(j)]  # Collect vectors from word 1 to j
            
            # Append the result as a tuple of (o_vector, v_vectors)
            results.append((o_vector, v_vectors))
    
    return results

extract_vectors(array_list_o[0], array_list_v[0])


[(array(['o_h1_w1_d1', 'o_h1_w1_d2'], dtype=object),
  [array(['v_h1_w1_d1', 'v_h1_w1_d2'], dtype=object)]),
 (array(['o_h1_w2_d1', 'o_h1_w2_d2'], dtype=object),
  [array(['v_h1_w1_d1', 'v_h1_w1_d2'], dtype=object),
   array(['v_h1_w2_d1', 'v_h1_w2_d2'], dtype=object)]),
 (array(['o_h1_w3_d1', 'o_h1_w3_d2'], dtype=object),
  [array(['v_h1_w1_d1', 'v_h1_w1_d2'], dtype=object),
   array(['v_h1_w2_d1', 'v_h1_w2_d2'], dtype=object),
   array(['v_h1_w3_d1', 'v_h1_w3_d2'], dtype=object)]),
 (array(['o_h1_w4_d1', 'o_h1_w4_d2'], dtype=object),
  [array(['v_h1_w1_d1', 'v_h1_w1_d2'], dtype=object),
   array(['v_h1_w2_d1', 'v_h1_w2_d2'], dtype=object),
   array(['v_h1_w3_d1', 'v_h1_w3_d2'], dtype=object),
   array(['v_h1_w4_d1', 'v_h1_w4_d2'], dtype=object)]),
 (array(['o_h2_w1_d1', 'o_h2_w1_d2'], dtype=object),
  [array(['v_h2_w1_d1', 'v_h2_w1_d2'], dtype=object)]),
 (array(['o_h2_w2_d1', 'o_h2_w2_d2'], dtype=object),
  [array(['v_h2_w1_d1', 'v_h2_w1_d2'], dtype=object),
   array(['v_h2_w2_d1', 

In [12]:

def extract_vectors(o_array, v_array):
    """
    Iterates through all heads (i) and all words (j), 
    extracting the o vector for each word j in head i 
    and all v vectors from word 1 to j in head i.

    Parameters:
    o_array (numpy array): Array of o vectors of shape (1, num_heads, num_words, num_dims)
    v_array (numpy array): Array of v vectors of shape (1, num_heads, num_words, num_dims)

    Returns:
    results (dict): A dictionary with keys indicating the head and word, 
                    and values being a tuple of (o_vector, v_vectors)
    """
    results = {}
    
    # Extract the shape info from arrays (since first dimension is 1, we use index 0)
    num_heads = o_array.shape[1]
    num_words = o_array.shape[2]
    
    # Iterate over each head and word
    for i in range(num_heads):
        for j in range(1, num_words + 1):  # 1-indexed for word loop
            # Extract o vector for word j in head i
            o_vector = o_array[0][i][j - 1]  # Subtract 1 because of 1-based indexing
            
            # Extract v vectors for all words from word 1 to word j in head i
            v_vectors = [v_array[0][i][w] for w in range(j)]  # Collect vectors from word 1 to j
            
            # Create a key to indicate the head and word
            key = f"head_{i + 1}_word_{j}"
            
            # Store the o_vector and v_vectors as a tuple in the dictionary
            results[key] = (o_vector, v_vectors)
    
    return results

extract_vectors(array_list_o[0], array_list_v[0])

{'head_1_word_1': (array(['o_h1_w1_d1', 'o_h1_w1_d2'], dtype=object),
  [array(['v_h1_w1_d1', 'v_h1_w1_d2'], dtype=object)]),
 'head_1_word_2': (array(['o_h1_w2_d1', 'o_h1_w2_d2'], dtype=object),
  [array(['v_h1_w1_d1', 'v_h1_w1_d2'], dtype=object),
   array(['v_h1_w2_d1', 'v_h1_w2_d2'], dtype=object)]),
 'head_1_word_3': (array(['o_h1_w3_d1', 'o_h1_w3_d2'], dtype=object),
  [array(['v_h1_w1_d1', 'v_h1_w1_d2'], dtype=object),
   array(['v_h1_w2_d1', 'v_h1_w2_d2'], dtype=object),
   array(['v_h1_w3_d1', 'v_h1_w3_d2'], dtype=object)]),
 'head_1_word_4': (array(['o_h1_w4_d1', 'o_h1_w4_d2'], dtype=object),
  [array(['v_h1_w1_d1', 'v_h1_w1_d2'], dtype=object),
   array(['v_h1_w2_d1', 'v_h1_w2_d2'], dtype=object),
   array(['v_h1_w3_d1', 'v_h1_w3_d2'], dtype=object),
   array(['v_h1_w4_d1', 'v_h1_w4_d2'], dtype=object)]),
 'head_2_word_1': (array(['o_h2_w1_d1', 'o_h2_w1_d2'], dtype=object),
  [array(['v_h2_w1_d1', 'v_h2_w1_d2'], dtype=object)]),
 'head_2_word_2': (array(['o_h2_w2_d1', 'o_h2_

In [15]:
adict = extract_vectors(oss[0], vss[0])

In [16]:
adict.keys()

dict_keys(['head_1_word_1', 'head_1_word_2', 'head_1_word_3', 'head_1_word_4', 'head_1_word_5', 'head_1_word_6', 'head_1_word_7', 'head_1_word_8', 'head_1_word_9', 'head_1_word_10', 'head_1_word_11', 'head_1_word_12', 'head_1_word_13', 'head_1_word_14', 'head_1_word_15', 'head_1_word_16', 'head_1_word_17', 'head_1_word_18', 'head_1_word_19', 'head_1_word_20', 'head_1_word_21', 'head_1_word_22', 'head_2_word_1', 'head_2_word_2', 'head_2_word_3', 'head_2_word_4', 'head_2_word_5', 'head_2_word_6', 'head_2_word_7', 'head_2_word_8', 'head_2_word_9', 'head_2_word_10', 'head_2_word_11', 'head_2_word_12', 'head_2_word_13', 'head_2_word_14', 'head_2_word_15', 'head_2_word_16', 'head_2_word_17', 'head_2_word_18', 'head_2_word_19', 'head_2_word_20', 'head_2_word_21', 'head_2_word_22', 'head_3_word_1', 'head_3_word_2', 'head_3_word_3', 'head_3_word_4', 'head_3_word_5', 'head_3_word_6', 'head_3_word_7', 'head_3_word_8', 'head_3_word_9', 'head_3_word_10', 'head_3_word_11', 'head_3_word_12', 'head_3_

In [24]:
oss[0].shape

torch.Size([1, 25, 22, 64])

In [30]:
oss[0][0][0][1]

tensor([ 6.8560e-03, -3.3396e-02,  7.1834e-03, -1.8522e-02, -4.9946e-04,
         2.3369e-02, -1.4819e-03, -2.1805e-03,  7.1396e-03, -7.8446e-03,
        -7.3506e-03,  7.0652e-03,  9.1161e-03,  1.6874e-02, -2.8840e-02,
         2.6108e-02, -3.7830e-03,  8.6572e-03,  3.5217e-02, -2.9596e-02,
        -3.9357e-04,  8.0426e-02, -4.3294e-02,  2.1639e-02, -1.7574e-02,
        -2.9265e-02, -3.7063e-02,  1.0623e-02, -3.3631e-04, -3.0488e-02,
        -1.3301e-02, -3.5427e-02,  2.4310e-02, -8.3496e-03, -6.2462e-03,
        -2.3183e-02,  1.2953e-02, -3.4075e-02, -1.4713e-02,  8.4200e-04,
         1.1093e-02, -1.1519e-02, -2.4327e-02, -3.1827e-02, -4.1753e-03,
         6.0492e-03, -7.6197e-03, -9.8767e-03,  1.4240e-02, -7.1642e-03,
        -6.7296e-03,  1.7374e-02, -4.0278e-03,  1.5930e-02, -1.3119e-02,
         2.2760e-02,  2.2517e-02, -4.2116e-02, -2.8315e-02,  2.3001e-02,
        -5.0896e-03, -5.2665e-05,  1.1372e-03, -2.5327e-03])

In [20]:
adict['head_1_word_2'][0]

tensor([ 6.8560e-03, -3.3396e-02,  7.1834e-03, -1.8522e-02, -4.9946e-04,
         2.3369e-02, -1.4819e-03, -2.1805e-03,  7.1396e-03, -7.8446e-03,
        -7.3506e-03,  7.0652e-03,  9.1161e-03,  1.6874e-02, -2.8840e-02,
         2.6108e-02, -3.7830e-03,  8.6572e-03,  3.5217e-02, -2.9596e-02,
        -3.9357e-04,  8.0426e-02, -4.3294e-02,  2.1639e-02, -1.7574e-02,
        -2.9265e-02, -3.7063e-02,  1.0623e-02, -3.3631e-04, -3.0488e-02,
        -1.3301e-02, -3.5427e-02,  2.4310e-02, -8.3496e-03, -6.2462e-03,
        -2.3183e-02,  1.2953e-02, -3.4075e-02, -1.4713e-02,  8.4200e-04,
         1.1093e-02, -1.1519e-02, -2.4327e-02, -3.1827e-02, -4.1753e-03,
         6.0492e-03, -7.6197e-03, -9.8767e-03,  1.4240e-02, -7.1642e-03,
        -6.7296e-03,  1.7374e-02, -4.0278e-03,  1.5930e-02, -1.3119e-02,
         2.2760e-02,  2.2517e-02, -4.2116e-02, -2.8315e-02,  2.3001e-02,
        -5.0896e-03, -5.2665e-05,  1.1372e-03, -2.5327e-03])

In [19]:
adict['head_1_word_2'][1]

[tensor([ 4.8211e-03, -3.3903e-02,  1.9640e-03, -2.1692e-02,  5.5888e-03,
          2.6403e-02, -4.0567e-03,  1.6367e-03,  5.3788e-03, -4.8036e-03,
         -1.1672e-02,  1.9453e-02,  1.0201e-02,  1.1253e-02, -3.5354e-02,
          2.5013e-02, -2.0711e-03, -7.9277e-04,  3.7744e-02, -2.4343e-02,
         -1.2822e-04,  7.5201e-02, -4.5358e-02,  2.2188e-02, -1.9178e-02,
         -2.7239e-02, -3.5703e-02,  1.0314e-02, -2.1588e-06, -3.5248e-02,
         -2.1442e-02, -3.2757e-02,  2.8156e-02, -7.2399e-03, -9.2617e-03,
         -1.6484e-02,  1.5226e-02, -3.0660e-02, -1.5372e-02,  3.4380e-03,
          1.5665e-02, -1.1248e-02, -1.9899e-02, -3.9064e-02,  4.1499e-03,
         -1.9762e-03, -1.1701e-02, -2.0029e-02,  1.5029e-02, -7.3606e-03,
         -2.7049e-03,  2.5045e-02, -3.7679e-03,  1.3631e-02, -1.5253e-02,
          2.1811e-02,  3.2364e-02, -4.3619e-02, -2.1905e-02,  2.2750e-02,
         -5.1420e-03, -8.4699e-03,  4.2160e-03, -3.4973e-03]),
 tensor([ 0.0306, -0.0275,  0.0682,  0.0185, -0.0

In [91]:
oss[0].squeeze().shape

torch.Size([25, 22, 64])

In [76]:
array_list[0].squeeze().shape

(5, 4, 2)

In [66]:
array_list[0].reshape(5, 4, 2)

array([[['h1_w1_d1', 'h1_w1_d2'],
        ['h1_w2_d1', 'h1_w2_d2'],
        ['h1_w3_d1', 'h1_w3_d2'],
        ['h1_w4_d1', 'h1_w4_d2']],

       [['h2_w1_d1', 'h2_w1_d2'],
        ['h2_w2_d1', 'h2_w2_d2'],
        ['h2_w3_d1', 'h2_w3_d2'],
        ['h2_w4_d1', 'h2_w4_d2']],

       [['h3_w1_d1', 'h3_w1_d2'],
        ['h3_w2_d1', 'h3_w2_d2'],
        ['h3_w3_d1', 'h3_w3_d2'],
        ['h3_w4_d1', 'h3_w4_d2']],

       [['h4_w1_d1', 'h4_w1_d2'],
        ['h4_w2_d1', 'h4_w2_d2'],
        ['h4_w3_d1', 'h4_w3_d2'],
        ['h4_w4_d1', 'h4_w4_d2']],

       [['h5_w1_d1', 'h5_w1_d2'],
        ['h5_w2_d1', 'h5_w2_d2'],
        ['h5_w3_d1', 'h5_w3_d2'],
        ['h5_w4_d1', 'h5_w4_d2']]], dtype=object)

In [68]:
array_list[0]

array([[[['h1_w1_d1', 'h1_w1_d2'],
         ['h1_w2_d1', 'h1_w2_d2'],
         ['h1_w3_d1', 'h1_w3_d2'],
         ['h1_w4_d1', 'h1_w4_d2']],

        [['h2_w1_d1', 'h2_w1_d2'],
         ['h2_w2_d1', 'h2_w2_d2'],
         ['h2_w3_d1', 'h2_w3_d2'],
         ['h2_w4_d1', 'h2_w4_d2']],

        [['h3_w1_d1', 'h3_w1_d2'],
         ['h3_w2_d1', 'h3_w2_d2'],
         ['h3_w3_d1', 'h3_w3_d2'],
         ['h3_w4_d1', 'h3_w4_d2']],

        [['h4_w1_d1', 'h4_w1_d2'],
         ['h4_w2_d1', 'h4_w2_d2'],
         ['h4_w3_d1', 'h4_w3_d2'],
         ['h4_w4_d1', 'h4_w4_d2']],

        [['h5_w1_d1', 'h5_w1_d2'],
         ['h5_w2_d1', 'h5_w2_d2'],
         ['h5_w3_d1', 'h5_w3_d2'],
         ['h5_w4_d1', 'h5_w4_d2']]]], dtype=object)

In [22]:
# Parameters
seq_len = 4       # Number of words/tokens in the sequence
num_layer = 3     # Number of layers in the model
num_head = 5      # Number of heads in each layer

# Initialize the list
data = []

# Generate the list based on the pattern
for ws in range(1, seq_len + 1):
    for l in range(1, num_layer + 1):
        for wt in range(1, seq_len + 1):
            for h in range(1, num_head + 1):
                data.append(f'ws{ws}_l{l}_h{h}_wt{wt}')

print(data)


['ws1_l1_h1_wt1', 'ws1_l1_h2_wt1', 'ws1_l1_h3_wt1', 'ws1_l1_h4_wt1', 'ws1_l1_h5_wt1', 'ws1_l1_h1_wt2', 'ws1_l1_h2_wt2', 'ws1_l1_h3_wt2', 'ws1_l1_h4_wt2', 'ws1_l1_h5_wt2', 'ws1_l1_h1_wt3', 'ws1_l1_h2_wt3', 'ws1_l1_h3_wt3', 'ws1_l1_h4_wt3', 'ws1_l1_h5_wt3', 'ws1_l1_h1_wt4', 'ws1_l1_h2_wt4', 'ws1_l1_h3_wt4', 'ws1_l1_h4_wt4', 'ws1_l1_h5_wt4', 'ws1_l2_h1_wt1', 'ws1_l2_h2_wt1', 'ws1_l2_h3_wt1', 'ws1_l2_h4_wt1', 'ws1_l2_h5_wt1', 'ws1_l2_h1_wt2', 'ws1_l2_h2_wt2', 'ws1_l2_h3_wt2', 'ws1_l2_h4_wt2', 'ws1_l2_h5_wt2', 'ws1_l2_h1_wt3', 'ws1_l2_h2_wt3', 'ws1_l2_h3_wt3', 'ws1_l2_h4_wt3', 'ws1_l2_h5_wt3', 'ws1_l2_h1_wt4', 'ws1_l2_h2_wt4', 'ws1_l2_h3_wt4', 'ws1_l2_h4_wt4', 'ws1_l2_h5_wt4', 'ws1_l3_h1_wt1', 'ws1_l3_h2_wt1', 'ws1_l3_h3_wt1', 'ws1_l3_h4_wt1', 'ws1_l3_h5_wt1', 'ws1_l3_h1_wt2', 'ws1_l3_h2_wt2', 'ws1_l3_h3_wt2', 'ws1_l3_h4_wt2', 'ws1_l3_h5_wt2', 'ws1_l3_h1_wt3', 'ws1_l3_h2_wt3', 'ws1_l3_h3_wt3', 'ws1_l3_h4_wt3', 'ws1_l3_h5_wt3', 'ws1_l3_h1_wt4', 'ws1_l3_h2_wt4', 'ws1_l3_h3_wt4', 'ws1_l3_h4_wt

In [27]:
# convert data to numpy array
import numpy as np
data = np.array(data)
data_new = data.reshape(seq_len, seq_len, num_layer, num_head)
data_new

array([[[['ws1_l1_h1_wt1', 'ws1_l1_h2_wt1', 'ws1_l1_h3_wt1',
          'ws1_l1_h4_wt1', 'ws1_l1_h5_wt1'],
         ['ws1_l1_h1_wt2', 'ws1_l1_h2_wt2', 'ws1_l1_h3_wt2',
          'ws1_l1_h4_wt2', 'ws1_l1_h5_wt2'],
         ['ws1_l1_h1_wt3', 'ws1_l1_h2_wt3', 'ws1_l1_h3_wt3',
          'ws1_l1_h4_wt3', 'ws1_l1_h5_wt3']],

        [['ws1_l1_h1_wt4', 'ws1_l1_h2_wt4', 'ws1_l1_h3_wt4',
          'ws1_l1_h4_wt4', 'ws1_l1_h5_wt4'],
         ['ws1_l2_h1_wt1', 'ws1_l2_h2_wt1', 'ws1_l2_h3_wt1',
          'ws1_l2_h4_wt1', 'ws1_l2_h5_wt1'],
         ['ws1_l2_h1_wt2', 'ws1_l2_h2_wt2', 'ws1_l2_h3_wt2',
          'ws1_l2_h4_wt2', 'ws1_l2_h5_wt2']],

        [['ws1_l2_h1_wt3', 'ws1_l2_h2_wt3', 'ws1_l2_h3_wt3',
          'ws1_l2_h4_wt3', 'ws1_l2_h5_wt3'],
         ['ws1_l2_h1_wt4', 'ws1_l2_h2_wt4', 'ws1_l2_h3_wt4',
          'ws1_l2_h4_wt4', 'ws1_l2_h5_wt4'],
         ['ws1_l3_h1_wt1', 'ws1_l3_h2_wt1', 'ws1_l3_h3_wt1',
          'ws1_l3_h4_wt1', 'ws1_l3_h5_wt1']],

        [['ws1_l3_h1_wt2', 'ws1_l3_h2_wt

In [24]:
data_new.shape

(4, 3, 5, 4)

In [26]:
data_new[0]

array([[['ws1_l1_h1_wt1', 'ws1_l1_h2_wt1', 'ws1_l1_h3_wt1',
         'ws1_l1_h4_wt1'],
        ['ws1_l1_h5_wt1', 'ws1_l1_h1_wt2', 'ws1_l1_h2_wt2',
         'ws1_l1_h3_wt2'],
        ['ws1_l1_h4_wt2', 'ws1_l1_h5_wt2', 'ws1_l1_h1_wt3',
         'ws1_l1_h2_wt3'],
        ['ws1_l1_h3_wt3', 'ws1_l1_h4_wt3', 'ws1_l1_h5_wt3',
         'ws1_l1_h1_wt4'],
        ['ws1_l1_h2_wt4', 'ws1_l1_h3_wt4', 'ws1_l1_h4_wt4',
         'ws1_l1_h5_wt4']],

       [['ws1_l2_h1_wt1', 'ws1_l2_h2_wt1', 'ws1_l2_h3_wt1',
         'ws1_l2_h4_wt1'],
        ['ws1_l2_h5_wt1', 'ws1_l2_h1_wt2', 'ws1_l2_h2_wt2',
         'ws1_l2_h3_wt2'],
        ['ws1_l2_h4_wt2', 'ws1_l2_h5_wt2', 'ws1_l2_h1_wt3',
         'ws1_l2_h2_wt3'],
        ['ws1_l2_h3_wt3', 'ws1_l2_h4_wt3', 'ws1_l2_h5_wt3',
         'ws1_l2_h1_wt4'],
        ['ws1_l2_h2_wt4', 'ws1_l2_h3_wt4', 'ws1_l2_h4_wt4',
         'ws1_l2_h5_wt4']],

       [['ws1_l3_h1_wt1', 'ws1_l3_h2_wt1', 'ws1_l3_h3_wt1',
         'ws1_l3_h4_wt1'],
        ['ws1_l3_h5_wt1', 'ws1_l3_h1_wt

In [89]:
sample = oss[0][0][0][0]
print(sample)
# apply torch tanh on sample
import torch
sample = torch.tensor(sample)
sample = torch.tanh(sample)
print('tanh:\n')
print(sample)
# apply arctan on sample
sample = torch.atan(sample)
print('arctan:\n')
print(sample)
# apply sigmoid on sample
sample = torch.sigmoid(sample)
print('sigmoid:\n')
print(sample)

tensor([ 4.8211e-03, -3.3903e-02,  1.9639e-03, -2.1692e-02,  5.5888e-03,
         2.6403e-02, -4.0567e-03,  1.6367e-03,  5.3788e-03, -4.8036e-03,
        -1.1672e-02,  1.9453e-02,  1.0201e-02,  1.1253e-02, -3.5354e-02,
         2.5013e-02, -2.0711e-03, -7.9277e-04,  3.7743e-02, -2.4343e-02,
        -1.2823e-04,  7.5201e-02, -4.5358e-02,  2.2188e-02, -1.9178e-02,
        -2.7239e-02, -3.5703e-02,  1.0314e-02, -2.1555e-06, -3.5248e-02,
        -2.1442e-02, -3.2757e-02,  2.8156e-02, -7.2399e-03, -9.2617e-03,
        -1.6484e-02,  1.5226e-02, -3.0660e-02, -1.5372e-02,  3.4380e-03,
         1.5665e-02, -1.1248e-02, -1.9899e-02, -3.9064e-02,  4.1499e-03,
        -1.9762e-03, -1.1701e-02, -2.0029e-02,  1.5029e-02, -7.3606e-03,
        -2.7049e-03,  2.5045e-02, -3.7679e-03,  1.3631e-02, -1.5253e-02,
         2.1811e-02,  3.2364e-02, -4.3619e-02, -2.1905e-02,  2.2750e-02,
        -5.1420e-03, -8.4699e-03,  4.2160e-03, -3.4973e-03])
tanh:

tensor([ 4.8211e-03, -3.3890e-02,  1.9639e-03, -2.1689e-